import Contact from '@/components/contact/Contact'
import Hero from '@/components/hero/Hero'
import Hero2 from '@/components/hero/Hero2'
import Hero3 from '@/components/hero/Hero3'
import Navbar from '@/components/navbar/Navbar'
import Review from '@/components/review/Review'
import Service from '@/components/service/Service'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='main-div'>
      <Navbar />

      <Hero3 />

      <Service />
      
      <Contact />

   

    <div className=' w-full h-[1240px]'>

    </div>
    </div>
    </>
  )
}
